// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkwZx98XSk7v5PQ60v0qJHLa1Kl3_lUGc',
    appId: '1:671974837174:web:69e10d4967e653441d0f17',
    messagingSenderId: '671974837174',
    projectId: 'nope-45b11',
    authDomain: 'nope-45b11.firebaseapp.com',
    storageBucket: 'nope-45b11.appspot.com',
    measurementId: 'G-QYMR9FPPDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9lVva_O-MUStQguFEN6-nwHY3Vafpf4c',
    appId: '1:671974837174:android:007827b960bac0c21d0f17',
    messagingSenderId: '671974837174',
    projectId: 'nope-45b11',
    storageBucket: 'nope-45b11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYxGM8nxgJYC3M0RU6XYIy0pkXAhYYKDc',
    appId: '1:671974837174:ios:23d94862b36e31d81d0f17',
    messagingSenderId: '671974837174',
    projectId: 'nope-45b11',
    storageBucket: 'nope-45b11.appspot.com',
    iosClientId: '671974837174-gs44uj1dpspgn6lijimt17aj6ua6fdms.apps.googleusercontent.com',
    iosBundleId: 'com.example.dayNight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYxGM8nxgJYC3M0RU6XYIy0pkXAhYYKDc',
    appId: '1:671974837174:ios:23d94862b36e31d81d0f17',
    messagingSenderId: '671974837174',
    projectId: 'nope-45b11',
    storageBucket: 'nope-45b11.appspot.com',
    iosClientId: '671974837174-gs44uj1dpspgn6lijimt17aj6ua6fdms.apps.googleusercontent.com',
    iosBundleId: 'com.example.dayNight',
  );
}
